# Generated by Django 3.1.7 on 2021-03-04 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=140)),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
