# Generated by Django 3.1.7 on 2021-03-04 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notifications_tweeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='tweet_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
