# Generated by Django 3.1.7 on 2021-03-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notifications_tweet_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='tweet_time',
        ),
    ]
