# Generated by Django 3.1.7 on 2021-03-05 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_auto_20210305_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeter',
            name='following',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
